FROM golang:1.21.6 AS builder

RUN apt-get -qq update

ENV GO111MODULE=on \
  CGO_ENABLED=0 \
  GOOS=linux \
  GOARCH=amd64

WORKDIR /app

COPY . .

RUN go build -o server ./server

FROM scratch

COPY --from=builder /app/server /
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

EXPOSE 3333

ENTRYPOINT ["/server"]